name: Build and deploy JAR app to Azure Web App - HealthNetBackend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '21'         # Specify just the version number
          distribution: 'microsoft'

      - name: Build with Maven
        run: mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          # Use a relative path so that when downloaded the jar is in the current directory.
          path: target/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    # Remove the dynamic URL from the environment as it isn’t available yet.
    environment:
      name: 'Production'
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'HealthNetBackend'   # Double-check that this matches your actual app name
          # If you’re not using a deployment slot, you can remove this line.
          slot-name: 'Production'
          # Specify the actual jar file path – if downloaded, it might now be in the workspace root.
          package: '*.jar'
